GuildCars/GuildCarsUI/GuildCarsUI/Models/ViewModel/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuildCarsUI.Models.ViewModel
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

GuildCars/GuildCarsUI/GuildCarsUI/Controllers/InventoryController.cs
using GuildCarsData;
using GuildCarsModel.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCarsUI.Controllers
{
    public class InventoryController : Controller
    {
        // GET: Inventory
        public ActionResult New()
        {
            IGuildCars repo = Settings.GetRepository();
            List<VehicleDisplay> model = new List<VehicleDisplay>();
            model = (repo.GetNew());
            return View(model);

        }
        public ActionResult Used()
        {
            IGuildCars repo = Settings.GetRepository();
            List<VehicleDisplay> model = new List<VehicleDisplay>();
            model = (repo.GetUsed());
            return View(model);
        }

        public ActionResult Details(int id) 
        {
            IGuildCars repo = Settings.GetRepository();
           VehicleDisplay model = new VehicleDisplay();
            model = (repo.GetById(id));
            return View(model);
        }

    }
}

GuildCars/GuildCarsUI/GuildCarsUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/css/Site.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <script src="~/js/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="separator"></li>
                    <li>@Html.ActionLink("New Inventory", "New", "Inventory")</li>
                    <li class="separator"></li>
                    <li>@Html.ActionLink("Used Inventory", "Used", "Inventory")</li>
                    <li class="separator"></li>
                    <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                    <li class="separator"></li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Sales")))
                    {
                        <li class="separator"></li>
                        <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                        if (User.IsInRole("Admin"))
                        {
                            <li class="separator"></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
                                    <li>@Html.ActionLink("Makes", "Makes", "Admin")</li>
                                    <li>@Html.ActionLink("Models", "Models", "Admin")</li>
                                    <li>@Html.ActionLink("Specials", "Specials", "Admin")</li>
                                    <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                                    <li>@Html.ActionLink("Vehicles", "Vehicles", "Admin")</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
              
            </div>
            <div class="navbar-right">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

GuildCars/GuildCarsUI/GuildCarsUI/Views/Shared/_Login.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="#">Hello @User.Identity.GetUserName()!</a>
        </li>
    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Log in", "Login", "Account")</li>
    </ul>
}